# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Run unit tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Checkout Current Repo
      uses: actions/checkout@v1
    - name: Install deps
      run: |
        pip install --upgrade pip pytest
        pip install -e .
    - name: Run tests
      run: |
        pytest -v
